---
- name: Install zsh
  package:
    name:
      - "powerline"
      - "zsh"
      - gpg
    state: latest
  become: yes

- name: Create user config dir
  file:
    path: "{{ home }}/.config"
    state: directory

- name: "Add nodejs apt key"
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: install_spaceship

- name: "Add nodejs 17.x ppa for apt repo"
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_17.x focal main
    update_cache: yes
  when: install_spaceship

- name: Install nodejs for Spaceship
  become: yes
  package:
    name:
      - nodejs
    state: latest
    update_cache: yes
  when: install_spaceship

- name: Download Starship
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: 0755
  when: install_starship

- name: Install Starship
  command: /tmp/starship_install.sh -y
  when: install_starship

- name: Copy Starship prompt config
  template:
    src: starship.toml.j2
    dest: "{{ home }}/.config/starship.toml"
  when: install_starship
