---
- name: Install zsh
  package:
    name:
      - "powerline"
      - "zsh"
      - gpg
    state: latest
  become: yes

- name: Create user config dir
  file:
    path: "{{ home }}/.config"
    state: directory

- name: Setup apt for nodejs 22.x
  become: yes
  block:
    - name: nodejs repo | gpg key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.asc
        mode: '0644'

    - name: nodejs | apt source
      ansible.builtin.apt_repository:
        filename: nodejs
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_22.x nodistro main
        state: present
        update_cache: true
  when: install_spaceship

- name: Install nodejs for Spaceship
  become: yes
  package:
    name:
      - nodejs
    state: latest
    update_cache: yes
  when: install_spaceship

- name: Download Starship
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: 0755
  when: install_starship

- name: Install Starship
  command: /tmp/starship_install.sh -y
  when: install_starship

- name: Copy Starship prompt config
  template:
    src: starship.toml.j2
    dest: "{{ home }}/.config/starship.toml"
  when: install_starship
