---
- hosts: localhost
  connection: local
  become: no
  gather_facts: yes

  vars:
    home: "/home/{{user}}"
    bashhub:
      set_env: yes
      server: "{{ bashhub_server }}"
    codeserver:
      auth: no # When using another front end auth
    install:
      awscli: yes
      bashhub: yes
      brew: no
      codeserver: yes
      docker_cli: yes
      gruntwork: yes
      hashicorp: yes
      kubernetes_cli: yes
      sops: yes
      ssh_server: yes
      terraform: yes
      tmux: yes
      vim: yes

  pre_tasks:
    - name: Set Version ENV
      become: yes
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^GOLIATH_VERSION'
        line: 'GOLIATH_VERSION={{ version }}'

  roles:
    - role: system_config
    - role: shell_config
    - role: markosamuli.linuxbrew
      linuxbrew_use_installer: true
      linuxbrew_init_shell: false
      linuxbrew_install_checksum: "sha256:9af575eb52eda83d546963db3ebed65d840738bc533ca195dcf3eb6ca2d6c7e7"
      when: install.brew
    - role: deekayen.awscli2
      when: install.awscli
