# Default system packages to install
system_packages:
  - locales
  - locales-all
  - curl
  - gpg
  - htop
  - net-tools
  - dnsutils
  - netcat-traditional
  - jq
  - make
  - dos2unix

# Configure which packages to install.
install:
  brew: no
  codeserver: no
  docker_cli: yes
  gruntwork: yes
  hashicorp: yes
  kubernetes_cli: yes
  sops: yes
  ssh_server: yes
  terraform: yes
  tmux: yes
  vim: yes

# If enabled above install these tools from Hashicorp repo.
# Terraform is installed seperately above.
hashicorp_tools:
  - packer

# Kf enabled above install these packages via brew.
# Note it seems most if not all brew packages increase image size significantly.
brew_packages:
  - lastpass-cli

codeserver:
  auth: yes # Disable if using your own auth such as authelia with traefik
