- name: Code Server | Download installer
  get_url:
    url: https://code-server.dev/install.sh
    dest: /tmp/codeserver-installer.sh
    mode: 0755

# Clearing VERSION env so it doesn't conflict with builder, otherwise have to set --version
- name: Code Server | Install
  command: /tmp/codeserver-installer.sh
  environment:
    VERSION: ""
