---
- name: Docker | Add APT key/repo
  become: yes
  block:
    - name: docker repo | no apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: docker | apt source
      ansible.builtin.apt_repository:
        filename: docker
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

- name: Docker | Install CLI
  become: yes
  package:
    name: docker-ce-cli
    state: latest

- name: Docker | Create group
  become: yes
  group:
    name: docker
    state: present

- name: Docker |  Add user to group
  become: yes
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
