---
- name: Docker | Add APT key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Docker | Add repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Docker | Install CLI
  become: yes
  package:
    name: docker-ce-cli
    state: latest

- name: Docker | Create group
  become: yes
  group:
    name: docker
    state: present

- name: Docker |  Add user to group
  become: yes
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
