- name: Gruntwork | Download installer
  get_url:
    url: https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh
    dest: /tmp/bootstrap-gruntwork-installer.sh
    mode: 0755

- name: Gruntwork | Get latest installer
  github_release:
    user: gruntwork-io
    repo: gruntwork-installer
    action: latest_release
  register: gruntwork_latest

- name: Gruntwork | Install
  command: /tmp/bootstrap-gruntwork-installer.sh --version {{ gruntwork_latest['tag'] }}

- name: Gruntwork | Get latest kubergrunt
  github_release:
    user: gruntwork-io
    repo: kubergrunt
    action: latest_release
  register: kubergrunt_latest

- name: Gruntwork | Install kubergrunt
  command: gruntwork-install --binary-name "kubergrunt" --repo "https://github.com/gruntwork-io/kubergrunt" --tag "{{ kubergrunt_latest['tag'] }}"
  when: install.kubernetes_cli

- name: Gruntwork | Get latest terragrunt
  github_release:
    user: gruntwork-io
    repo: terragrunt
    action: latest_release
  register: terragrunt_latest

- name: Gruntwork | Install terragrunt
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_latest['tag'] }}/terragrunt_linux_amd64
    dest: "{{ home }}/.bin/terragrunt"
    mode: 0700
  when: install.terraform
