---
- name: Hashicorp | Add APT key
  become: yes
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Hashicorp | Add repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Hashicorp | Install packages
  become: yes
  package:
    name: "{{ hashicorp_tools }}"
    state: latest
  when: install.hashicorp

- name: Hashicorp | Install terrarform
  become: yes
  package:
    name: terraform
    state: latest
  when: install.terraform

- name: Hashicorp | Get latest tfswitch
  github_release:
    user: warrensbox
    repo: terraform-switcher
    action: latest_release
  register: tfswitch_latest

- name: Hashicorp | Set tfswitch version
  set_fact:
    tfswitcher_version: "v{{ tfswitch_latest['tag'] | regex_replace('^v','') }}"

- name: Hashicorp | Set tfswitch filename
  set_fact:
    tfswitcher_filename: "terraform-switcher_{{ tfswitcher_version }}_linux_amd64.tar.gz"

- name: Hashicorp | Download tfswitch
  get_url:
    url: "https://github.com/warrensbox/terraform-switcher/releases/download/{{ tfswitcher_version }}/{{ tfswitcher_filename }}"
    dest: "/tmp/"
    mode: 0600
  when: install.terraform

- name: Hashicorp | Unarchive tfswitch
  ansible.builtin.unarchive:
    src: "/tmp/{{ tfswitcher_filename }}"
    dest: "{{ home }}/.bin/"
    exclude:
      - README.md
      - LICENSE
    mode: 0700
    remote_src: yes
  when: install.terraform

- name: Hashicorp | tfswitch usage https://tfswitch.warrensbox.com/Install/
  ansible.builtin.debug:
    msg: "To use tfswitch use alias tfs <VERSION>. You can use tfswitch -l to list but not switch."
  when: install.terraform

- name: Hashicorp | Get latest terraform
  github_release:
    user: hashicorp
    repo: terraform
    action: latest_release
  register: terraform_latest

- name: Hashicorp | tfswitch first run
  command: "{{ home }}/.bin/tfswitch -b {{ home }}/.bin/terraform {{ terraform_latest['tag'] | regex_replace('^v','') }}"
  when: install.terraform

- name: Hashicorp | Terraform Cache Dir
  file:
    path: "{{ home }}/.terraform.d/plugin-cache"
    state: directory
  when: install.terraform

- name: Hashicorp | Configure terraform Cache Dir
  copy:
    dest: "{{ home }}/.terraformrc"
    content: |
      plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
  when: install.terraform
