---
- name: System | Install packages
  become: yes
  package:
    name: "{{ system_packages }}"
    state: latest

- name: System | Create user bin
  file:
    path: "{{ home }}/.bin"
    state: directory

- name: System | Install Bat https://github.com/sharkdp/bat
  become: yes
  package:
    name: bat
    state: latest

- name: Github | Add APT key/repo
  become: yes
  block:
    - name: github repo | no apt key
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /etc/apt/keyrings/github.gpg
        mode: '0644'

    - name: github | apt source
      ansible.builtin.apt_repository:
        filename: github
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/github.gpg] https://cli.github.com/packages stable main
        state: present
        update_cache: true

- name: System | Install Github CLI
  become: yes
  package:
    name: gh
    state: latest

# Enable once ubuntu has ansible-core 2.17 and remove from dockerfile
# - name: System | Install github python package for ansible github_releases
#   ansible.builtin.pip:
#     name: github3.py
#     break_system_packages: true #okay since there isn't a apt install of this