---
- name: System | Install packages
  become: yes
  package:
    name: "{{ system_packages }}"
    state: latest

- name: System | Create user bin
  file:
    path: "{{ home }}/.bin"
    state: directory

- name: System | Get Latest Bat
  github_release:
    user: sharkdp
    repo: bat
    action: latest_release
  register: bat_latest

- name: System | Download bat
  get_url:
    url: https://github.com/sharkdp/bat/releases/download/{{ bat_latest['tag'] }}/bat_{{ bat_latest['tag'] | regex_replace('^v','') }}_amd64.deb
    dest: "/tmp/"

- name: System | Install bat
  become: yes
  apt:
    deb: "/tmp/bat_{{ bat_latest['tag'] | regex_replace('^v','') }}_amd64.deb"

- name: System | Add Github APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 23F3D4EA75716059
    state: present

- name: System | Add Github repo
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://cli.github.com/packages {{ ansible_distribution_release }} stable main"
    state: present
    update_cache: true

- name: System | Install Github CLI
  become: yes
  package:
    name: gh
    state: latest
