" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

if has("syntax")
  syntax on
endif

set background=dark

" This makes ruby look nice :)
colorscheme elflord

"show existing tab with 4 spaces width
set tabstop=4
"when indenting with '>', use 4 spaces width
set shiftwidth=4
"On pressing tab, insert 4 spaces
set expandtab

" Enable line numbers
set number


" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd            " Show (partial) command in status line.
set showmatch          " Show matching brackets.
set ignorecase         " Do case insensitive matching
set smartcase          " Do smart case matching
set incsearch          " Incremental search
set autowrite          " Automatically save before commands like :next and :make
set hidden             " Hide buffers when they are abandoned

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" F1 Toggles "Line Numbers"
" F2 Toggles "Smart Paste" (to preserve indentation while pasting)
" F3 Toggles "Line Wrap"
noremap <silent> <F1> :set number!<CR>
noremap <F2> :set paste! paste?<CR>
noremap <F3> :set wrap! wrap?<CR>
imap <F2> <C-O><F2>
imap <F3> <C-O><F3>

" End /etc/vim/vimrc
